### PR TITLE
fixing sqaushed merge

### PR DESCRIPTION
**Pull request by BleakleyMcD**

### CODE REVIEW

**Comment by BleakleyMcD** [comment]
@dericed I deleted the conflict and merged this. The script looks fine in the github repo and also fine on my local git repo. I can run the local from my git repo with no issue. BUT, the homebrew installed version isn't updating. `which makemediainfo` returns `/opt/homebrew/bin/makemediainfo` and `cat /opt/homebrew/bin/makemediainfo` shows me that the script still has the unresolved conflicts and so that script is NG. I've run `brew update` `brew upgrade` and `reinstall nmaahcmm` but none fix the `/opt/homebrew/bin/makemediainfo` and bring it in sync with the repo . What do I need to do?

**Comment by BleakleyMcD** [comment]
@dericed 
```
/Users/bleakley/github/bleakley/documentation/copyright_research
≈:≈ brew doctor
Your system is ready to brew.
                                                                                                                                                                                                        
/Users/bleakley/github/bleakley/documentation/copyright_research
≈:≈ brew link --force --overwrite nmaahcmm
Warning: Already linked: /opt/homebrew/Cellar/nmaahcmm/0.0.5_1
To relink, run:
  brew unlink nmaahcmm && brew link nmaahcmm
                                                                                                                                                                                                        
/Users/bleakley/github/bleakley/documentation/copyright_research
≈:≈ brew unlink nmaahcmm && brew link nmaahcmm
Unlinking /opt/homebrew/Cellar/nmaahcmm/0.0.5_1... 23 symlinks removed.
Linking /opt/homebrew/Cellar/nmaahcmm/0.0.5_1... 23 symlinks created.
                                                                                                                                                                                                        
/Users/bleakley/github/bleakley/documentation/copyright_research
≈:≈ which makemediainfo
/opt/homebrew/bin/makemediainfo
                                                                                                                                                                                                        
/Users/bleakley/github/bleakley/documentation/copyright_research
≈:≈ cat /opt/homebrew/bin/makemediainfo
```
still has the unfixed script at `/opt/homebrew/bin/makemediainfo`

**Comment by BleakleyMcD** [comment]
@chialinchou1 is also having this problem. why is this one script not updating?

@dericed

**Comment by dericed** [comment]
@BleakleyMcD can you review https://github.com/NMAAHC/homebrew-nmaahcmm/pull/9

**Pull request merged**
